// Tray — the persistent macOS menu-bar surface for Hark.
//
// Why a separate module: the main process is built with plain `tsc`
// (tsconfig.main.json) and has NO asset-copy step, so a loose .png in
// src/main would never land in dist/main. The two glyphs are therefore
// embedded as base64 PNGs below and rehydrated with
// nativeImage.createFromBuffer at runtime — zero filesystem dependency.
//
// The glyphs are TEMPLATE images (`setTemplateImage(true)`): macOS ignores
// their RGB and recolors them from the alpha channel to match light/dark
// menu bars and selection state. Idle is a hollow ring (subtle), recording
// is a filled dot (obvious). 16px logical + 32px @2x so Retina stays crisp.
//
// State note: capture/connection state lives in the renderer's
// EngineService. The renderer pushes a snapshot here via
// `window.hark.setTrayState(...)`; this module re-derives the icon and the
// menu-item enablement from that snapshot. There is NO "paused" state —
// pause is an engine stub, so the icon is binary idle/recording.

import {
  Tray,
  Menu,
  nativeImage,
  NativeImage,
  BrowserWindow,
  MenuItemConstructorOptions,
} from 'electron';

/**
 * Snapshot of the renderer's capture/connection state, pushed over IPC.
 * Mirrors the `TrayState` shape exposed in preload.ts and consumed by the
 * `window.hark.setTrayState` contract in engine.service.ts.
 */
export interface TrayState {
  capturing: boolean;
  ready: boolean;
  connected: boolean;
}

/** Action strings sent main → renderer. Whitelisted; see preload.ts. */
export type TrayAction = 'start' | 'stop';

// ─── Embedded template glyphs (base64 PNG, generated offline) ──────────
// Idle: hollow ring. Recording: filled dot. Black + alpha; template mode
// makes macOS recolor them. Generated by a pure-Node PNG encoder so there
// is no canvas/asset dependency in the build.
const ICON_IDLE_1X =
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAY0lEQVR42mNgGMzAgIGBoQCKDUjVeJ6BgeE/Gj5PjEEgBe+hGuYzMDAEQPF8qNh7QobAbE7AIpeA5BKctsNsxgVgLsHqigKoZAAeAwKgagpoYgDFXqA4EKkSjRQnJKokZfoCAHQuMZXb/IVgAAAAAElFTkSuQmCC';
const ICON_IDLE_2X =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAwElEQVR42u2W3Q2FIAyFvxEYhVEc4Y7iBozECIzgCHcEfelNCMEoRVNuwkn6ov2h7SkUJib+EAsQgAgkkSjfljcDf4AN2C9kE93H4CTDvVGi2HYHTycBfqWPFzpdh6hlvp44dfKvVgl1z3NHX8DfsPOim9uqOFESzjfY+goxm0etLHsrynY0jWgojJ2SwLmPoCVf6iBx0pIxPcHinkTMD2DeAnMSmo+h+UU0xFVs/hgN8RybLyRDrGTDLKUTE6/gAG0RyLWk/GZ5AAAAAElFTkSuQmCC';
const ICON_REC_1X =
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAUElEQVR42mNgGMzAgIGBoQCKDUjVeJ6BgeE/Gj5PjEEgBe+xaIbh94QMOY9HM7JLcNr+n0iM1RUFJBhQQBMDKPYCxYFIlWikOCFRJSnTFwAAN6lcacekytYAAAAASUVORK5CYII=';
const ICON_REC_2X =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAlUlEQVR42u2Wyw3AIAxD3wgdrSN0I0bKCBmBUegllXqrCNCAhCVfEMiGfAhsbCyIE0iAAGoUWztHCl9ABsoHs+3thsNuWCopdrZZXB3iD7XVhDSIv1/CHfPSia6cyB0NZE+plc6sKtE0wED6O/maklEHGNClDISHIDwJw8swvBFN0YrDP6MpvuPwgWSKkWyaoXRjYwhu8IFx2Ecwj8MAAAAASUVORK5CYII=';

function decode(b64: string): Buffer {
  return Buffer.from(b64, 'base64');
}

/** Build a 16px template image with its 32px @2x representation attached. */
function makeTemplateImage(b1x: string, b2x: string): NativeImage {
  const img = nativeImage.createFromBuffer(decode(b1x), { scaleFactor: 1 });
  img.addRepresentation({
    scaleFactor: 2,
    buffer: decode(b2x),
  });
  img.setTemplateImage(true);
  return img;
}

/**
 * Owns the single Tray instance and the menu it presents. Construct once,
 * after `app.whenReady()`. `onAction` is invoked for Start/Stop (forwarded
 * to the renderer); `onToggleWindow` and `onQuit` are handled in main.
 */
export class HarkTray {
  private readonly tray: Tray;
  private readonly idleIcon: NativeImage;
  private readonly recIcon: NativeImage;
  private state: TrayState = { capturing: false, ready: false, connected: false };

  constructor(opts: {
    getWindow(): BrowserWindow | null;
    onAction(action: TrayAction): void;
    onToggleWindow(): void;
    onQuit(): void;
  }) {
    this.idleIcon = makeTemplateImage(ICON_IDLE_1X, ICON_IDLE_2X);
    this.recIcon = makeTemplateImage(ICON_REC_1X, ICON_REC_2X);

    this.tray = new Tray(this.idleIcon);
    this.tray.setToolTip('Hark');
    // Left-clicking the icon just presents the context menu — on macOS
    // Electron pops the menu automatically once one is set (rebuildMenu
    // below), so no 'click' handler. Showing/hiding the window is an
    // explicit choice via the menu's Show/Hide item (which still calls
    // onToggleWindow); the bare icon click never toggles the window.

    this.onAction = opts.onAction;
    this.onToggleWindow = opts.onToggleWindow;
    this.onQuit = opts.onQuit;
    this.getWindow = opts.getWindow;

    this.rebuildMenu();
  }

  private readonly onAction: (action: TrayAction) => void;
  private readonly onToggleWindow: () => void;
  private readonly onQuit: () => void;
  private readonly getWindow: () => BrowserWindow | null;

  /** Push a fresh state snapshot from the renderer; updates icon + menu. */
  setState(next: TrayState): void {
    this.state = next;
    this.tray.setImage(next.capturing ? this.recIcon : this.idleIcon);
    // Belt-and-suspenders for non-template fallbacks: title stays empty so
    // the bar isn't cluttered, but flips to a dot if the image ever fails
    // to render. Harmless when the template image is showing.
    this.tray.setToolTip(next.capturing ? 'Hark — recording' : 'Hark');
    this.rebuildMenu();
  }

  private rebuildMenu(): void {
    const win = this.getWindow();
    const visible = !!win && win.isVisible();
    const { capturing, ready, connected } = this.state;

    const template: MenuItemConstructorOptions[] = [
      {
        label: visible ? 'Hide Hark' : 'Show Hark',
        click: () => this.onToggleWindow(),
      },
      { type: 'separator' },
      {
        label: 'Start Capture',
        enabled: connected && ready && !capturing,
        click: () => this.onAction('start'),
      },
      {
        label: 'Stop Capture',
        enabled: capturing,
        click: () => this.onAction('stop'),
      },
      { type: 'separator' },
      {
        label: 'Quit Hark',
        accelerator: 'Command+Q',
        click: () => this.onQuit(),
      },
    ];

    this.tray.setContextMenu(Menu.buildFromTemplate(template));
  }

  /** Tear down the tray (called on quit so the icon disappears promptly). */
  destroy(): void {
    this.tray.destroy();
  }
}
